sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js:
  - '6'
before_install:
  - npm i
script:
  - ./node_modules/@angular/cli/bin/ng test -w false
  - ./node_modules/@angular/cli/bin/ng e2e -w false
  - ./node_modules/@angular/cli/bin/ng lint
